### ISSUE TITLE
Ability to target elements within theme.json

### ISSUE THREAD

**Issue by slocker3** [happyprime/show-hide-section#78]
My expectation is that the `summary` element should be available to style via theme.json.

Example:
```
"happyprime/show-hide-section": {
      "elements": {
	      "summary": {
		      "typography": {
			      "fontWeight": "700"
		      }
	      }
      }
},
```

**Comment by slocker3** [comment]
Another option is if `summary` could be turned into a block as well `happyprime/show-hide-section-summary`. This would probably solve the issues I am having.

**Comment by jeremyfelt** [comment]
>Another option is if summary could be turned into a block as well happyprime/show-hide-section-summary. This would probably solve the issues I am having.

This is a thing now via #91!
